#ifndef __NEPTUNUS_CONFIG_H
#define __NEPTUNUS_CONFIG_H

#define CONFIG_SKIP_LOWLEVEL_INIT

#define CONFIG_ENV_IS_NOWHERE	1
#define CONFIG_ENV_SIZE		0x4000

#define CPU_CLOCK_RATE              12500000
#define CONFIG_SYS_MIPS_TIMER_FREQ  (CPU_CLOCK_RATE >> 1)

#define CONFIG_SYS_SDRAM_BASE		0x80000000
#define CONFIG_SYS_SDRAM_SIZE		0x00800000	/* 8 Mbytes */
#define CONFIG_SYS_INIT_SP_ADDR		\
	(CONFIG_SYS_SDRAM_BASE + CONFIG_SYS_SDRAM_SIZE - 0x1000)

#define CONFIG_SYS_MALLOC_LEN		(256 << 10)

#define CONFIG_SYS_LOAD_ADDR            CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_MONITOR_BASE  0xbe000000

#define CONFIG_SYS_NO_FLASH

#define CONFIG_SYS_CBSIZE   1024
#define CONFIG_BAUDRATE     115200

#define CONFIG_SYS_MAXARGS  16

/* DM9000 */
#define CONFIG_DRIVER_DM9000
#define CONFIG_DM9000_NO_SROM
// #define CONFIG_NET_RANDOM_ETHADDR
// #define CONFIG_DM9000_DEBUG
#define CONFIG_DM9000_BASE    0xBFD00404
#define DM9000_IO             (CONFIG_DM9000_BASE + 4)
#define DM9000_DATA           (CONFIG_DM9000_BASE)

#define CONFIG_SYS_LONGHELP

#define CONFIG_CMD_CLK
#define CONFIG_CMD_GETTIME
#define CONFIG_CMD_TIMER
#define CONFIG_CMD_DHCP
#define CONFIG_CMD_PING

#endif // __NEPTUNUS_CONFIG_H
